### ISSUE TITLE
Duplicate themes and tags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/schedule-app-core#199]
The first time I visit Categories or Tags via the header links, I usually see the list duplicated. If I leave and return to the list, it displays properly. I've seen this on app for different demo events. Probably via latest Chrome browser on OS X. Strange.

**Comment by mmmavis** [comment]
Seems like a webkit problem. i was able to reproduce this issue on Safari. Will look into it.

**Comment by mmmavis** [comment]
I think the problem is cuz Chrome(/webkit browsers) and Firefox treat popstate event differently. 
```js
window.history.ready = true;
```
(from [this line](https://github.com/mozilla/schedule-app-core/blob/b564e03ffbd347e3ad65530f1c84e9e9227d0a4b/js/schedule.js#L383)) triggers [popstate](https://github.com/mozilla/schedule-app-core/blob/b564e03ffbd347e3ad65530f1c84e9e9227d0a4b/js/schedule.js#L927-L933) on Webkit browser and therefore things get loaded twice.
